### ISSUE TITLE
Somatória do Transifex

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/OSMBtranstats#10]
Talvez eu tenha feito errado a somatória para os _resources_ do Transifex. Parece que não deveria ter considerado palavras (words). Falo assim, ligeiro, porque estou sem tempo de ver isso com calma.

**Comment by alexandre-mbm** [comment]
Na [API do Transifex](http://docs.transifex.com/developer/api/statistics), para **um** recurso, temos dados como os seguintes:

``` json
"pt_BR": {
    "reviewed_percentage": "92%",
    "completed": "93%",
    "untranslated_words": 1209,
    "last_commiter": "diegobz",
    "reviewed": 27,
    "translated_entities": 2035,
    "translated_words": 15420,
    "last_update": "2014-02-20 14:25:01",
    "untranslated_entities": 130
},
```

Para o cálculo com múltiplos _resources_, invés de _words_, parece que devemos usar _entities_.

**Comment by willemarcel** [comment]
O campo "completed" não basta?

Projeto legal esse! Se precisar de scrapping de alguma página, me fala que posso fazer (em Python).

**Comment by alexandre-mbm** [comment]
@willemarcel, sim, o "completed" basta e é usado, _para quando **um** resource é especificado_. Mas a issue diz respeito a quando resource não é especificado e quer-se somar a situação dos múltiplos resources de um projeto traduzido em Transifex. É como se dá com as sources  "Wheelmap - Site" e "Wheelmap - Android app" (veja [aqui](../blob/2c150ddbc6e64c0e9d32939ee1199b80276167bf/config.yml#L91) e [aqui](../blob/2c150ddbc6e64c0e9d32939ee1199b80276167bf/get_stats.rb#L64)).

Para a necessidade presente, todo o scrapping já está feito e funcional. A implementação está nos arquivos `*_collectors.rb`. Para HTML é usado o nokogiri com [seleção por CSS](../blob/2c150ddbc6e64c0e9d32939ee1199b80276167bf/noko_collectors.rb#L48).

Se surgirem novas necessidades e você quiser usar Python, eu posso plugar seu resultado no modelo de objetos existente em Ruby. Porém, introduzir o Python aumentaria a complexidade em termos de gerenciamento de dependências de software. Sinceramente, eu preferiria que você e demais colaboradores se interessassem pelas facilitades do Ruby já exemplificadas nos coletores.

Eu cogitei fazer em Python e preferi Ruby.

Pensei que ia fazer em um dia, e foram quatro. Pouco mais de 600 linhas. Mas pausei várias vezes. Nesse momento, o resultado (código wiki gerado) está completo. Restam as issues...

**Comment by jgpacker** [comment]
Acho que poderia relatar as porcentagens separadas no wiki mesmo, só traduzindo o nome dos _resources_. Por exemplo, no iD seria "principal" ou "núcleo" para "_core_" e "predefinições" para "_presets_".

**Comment by alexandre-mbm** [comment]
Ou não traduzindo...

Acho que podemos criar isso como opção. Na configuração, um `:list_resources: true` (para a source). Com ou sem isso, de todo jeito, usar _words_ no que já está feito parece errado. Penso que devemos corrigir para 'entities' e ficar abertos ao modo opcional de funcionamento. Dentro da célula, ele faria:

```
Total: 84.2%
- resource_x: 10%
- resource_y: 15.7%
- resource_z: 13.4%
```

Acho isso interessante. Tenho vontade de fazer. Mas no momento, hoje, estou cansando ou sem ânimo.

---

Pensei mais.

OK, @jgpacker, tradução também poderia ser opcional. Algo assim nas configurações:

``` yaml
:list_resources: true
    - :name: core
      :pt_BR: núcleo
    - :name: presets
      :pt_BR: predefinições
```

**Comment by alexandre-mbm** [comment]
A issue foi fechada com a "correção", para encerramento do milestone. Vejam #16.
