### ISSUE TITLE
Coincidências em arquivos de tradução YAML

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/OSMBtranstats#11]
Tem sido tratadas como chaves "não traduzidas". Mas, pensando bem... os mantenedores dos arquivos de tradução não deixariam aquelas chaves no arquivo do _resource_dest_ com essa lógica. Pelo contrário, talvez a coincidência apenas sempre faça constar que aquela chave sem tradução nunca será traduzida. Concordam?

@OSMBrasil/owners

**Comment by alexandre-mbm** [comment]
@jgpacker, o que você acha?

**Comment by jgpacker** [comment]
Acho que a única coisa que poderia fazer (se possível), é manualmente excluir do arquivo da tradução em pt-BR as linhas que não foram traduzidas. Consequentemente, tudo que estiver no arquivo em português do Brasil vai ser algo traduzido, estando igual ao inglês ou não.

**Comment by alexandre-mbm** [comment]
OK. Então você concordou. Corrigirei para ficar assim.

**Comment by Skippern** [comment]
Se o .YAML contem as frases não traduzido em Ingles, faz um diff entre o pt-BR e o en, conta somente os que e diferente e dividir por quantidade total via dar o percentagem traduzido

**Comment by jgpacker** [comment]
Magno, o arquivo de tradução pt-BR do taginfo já deve estar assim (sem linhas não-traduzidas).

**Comment by alexandre-mbm** [comment]
@Skippern, o diff já é [muito bem] feito pelo yamldiff. Eu é que estou fazendo operações erradas com os resultados. Mas isso vai ser muito fácil de corrigir. Entendi: tanto eu, como você, como @jgpacker, concordamos que as coincidências devem ser contadas como "coisa traduzida".

Hoje à tarde eu saí, e acabo de chegar. Vou pegar no [milestone](../milestones/Finalização do início) agora.

## 

@jgpacker, @Skippern, na verdade, acho que todos os projetos fazem assim. Não tem por que o gerente deixar o pt_BR.yml "sujo", com coisa que deve ser traduzida mas não está. Trazer essa suheira para o pt_BR.yml só é útil enquanto se trabalha no arquivo. Não o é para persisti-lo assim. De outro modo, somente seria possível "gerenciar a realidade" com uma lista de chaves ignoradas, tal como eu fiz no [locale_merge.rb](https://gist.github.com/alexandre-mbm/c3a19edd3303d955d803) usando um arquivo _ignore_.
