### ISSUE TITLE
Links diretos para as traduções

### ISSUE THREAD

**Issue by vgeorge** [OSMBrasil/OSMBtranstats#12]
Nas primeiras versões da tabela havia links diretos para as páginas de tradução. Como fazemos para eles aparecerem novamente?

**Comment by alexandre-mbm** [comment]
Falta implementar. Eu já estava contando com isso. Fiquei um pouco acanhado em substituir a página na wiki por causa disso. Implementemos! Se alguém não tiver paciência a respeito disso, faça na minha frente. Hoje eu acho que vou descansar. ~~A URL poderá ser pega do coletor.~~

Os coletores não precisam implementar rigidamente uma interface mínima tal como acontece com as subcalsses de ItemParser. Ainda assim, tentei me ater a sempre fornecer um `completed()`. Já aconteceu diferente, com o coletor do Taginfo, o qual tem `completed_keys()` e `completed_tags()`.

Mas eu também vejo que links ou código wiki extra podem ser pegos de config.yml. Minha vontade é usar decoradores para unir todas as informações na `message` que é "resultada" pelo ItemParser.

**Comment by alexandre-mbm** [comment]
Melhor fazer uma modelagem de decoradores. Eles decorarão ao menos com uma URL, inicialmente. ~~Serão instanciados por cada *Parser, a exemplo dos *Collector.~~ **Pretendo fazer isso a amanhã.**

Eu tinha esquecido: a URL nos coletores é para scrapping. Não atribuamos outra tarefa a eles.

---

Para referência, temos a [primeira versão da tabela](http://wiki.openstreetmap.org/w/index.php?title=WikiProject_Brazil/Tradu%C3%A7%C3%B5es/Situa%C3%A7%C3%A3o&oldid=1135839) de situação de traduções.

**Notas:**
- Não se apontará mais para diffs referentes a Mapillary e Taginfo
- OSMAnd receberá apenas um link, em cima do percentual, tal como os demais
- Em suma, haverá um super decorador geral (com suas subclasses e um decorador para taginfo)
- É conveniente ter uma fábrica de decoradores
- É conveniente lembrar que a tabela poderá ganhar colunas; por exemplo, uma de "Última data"
- A cada coluna poderá corresponder uma decoração
